import { Todo } from "src/app/models/todo.model";

export const TODOS: Todo[] = [
  {id: 1, label: "Stand in line at the post office and keep letting people skip you.", important: false, done: false},
  {id: 2, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 3, label: "Wash a cup.", important: false, done: false},
  {id: 4, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 5, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 6, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 7, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 8, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 9, label: "Pretend to be a rug.", important: false, done: false},
  {id: 10, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 11, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 12, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 13, label: "Wash a cup.", important: false, done: false},
  {id: 14, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 15, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 16, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 17, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 18, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 19, label: "Pretend to be a rug.", important: false, done: false},
  {id: 20, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 21, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 22, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 23, label: "Wash a cup.", important: false, done: false},
  {id: 24, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 25, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 26, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 27, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 28, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 29, label: "Pretend to be a rug.", important: false, done: false},
  {id: 30, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 31, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 32, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 33, label: "Wash a cup.", important: false, done: false},
  {id: 34, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 35, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 36, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 37, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 38, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 39, label: "Pretend to be a rug.", important: false, done: false},
  {id: 40, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 41, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 42, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 43, label: "Wash a cup.", important: false, done: false},
  {id: 44, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 45, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 46, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 47, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 48, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 49, label: "Pretend to be a rug.", important: false, done: false},
  {id: 50, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 51, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 52, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 53, label: "Wash a cup.", important: false, done: false},
  {id: 54, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 55, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 56, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 57, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 58, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 59, label: "Pretend to be a rug.", important: false, done: false},
  {id: 60, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 61, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 62, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 63, label: "Wash a cup.", important: false, done: false},
  {id: 64, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 65, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 66, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 67, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 68, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 69, label: "Pretend to be a rug.", important: false, done: false},
  {id: 70, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 71, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 72, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 73, label: "Wash a cup.", important: false, done: false},
  {id: 74, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 75, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 76, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 77, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 78, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 79, label: "Pretend to be a rug.", important: false, done: false},
  {id: 80, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 81, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 82, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 83, label: "Wash a cup.", important: false, done: false},
  {id: 84, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 85, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 86, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 87, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 88, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 89, label: "Pretend to be a rug.", important: false, done: false},
  {id: 90, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 91, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 92, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 93, label: "Wash a cup.", important: false, done: false},
  {id: 94, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 95, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 96, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 97, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 98, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 99, label: "Pretend to be a rug.", important: false, done: false},
  {id: 100, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 101, label: "Stand in line at the post office and keep letting people skip you.", important: false, done: false},
  {id: 102, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 103, label: "Wash a cup.", important: false, done: false},
  {id: 104, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 105, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 106, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 107, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 108, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 109, label: "Pretend to be a rug.", important: false, done: false},
  {id: 110, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 111, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 112, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 113, label: "Wash a cup.", important: false, done: false},
  {id: 114, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 115, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 116, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 117, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 118, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 119, label: "Pretend to be a rug.", important: false, done: false},
  {id: 120, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 121, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 122, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 123, label: "Wash a cup.", important: false, done: false},
  {id: 124, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 125, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 126, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 127, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 128, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 129, label: "Pretend to be a rug.", important: false, done: false},
  {id: 130, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 131, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 132, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 133, label: "Wash a cup.", important: false, done: false},
  {id: 134, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 135, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 136, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 137, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 138, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 139, label: "Pretend to be a rug.", important: false, done: false},
  {id: 140, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 141, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 142, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 143, label: "Wash a cup.", important: false, done: false},
  {id: 144, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 145, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 146, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 147, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 148, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 149, label: "Pretend to be a rug.", important: false, done: false},
  {id: 150, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 151, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 152, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 153, label: "Wash a cup.", important: false, done: false},
  {id: 154, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 155, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 156, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 157, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 158, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 159, label: "Pretend to be a rug.", important: false, done: false},
  {id: 160, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 161, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 162, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 163, label: "Wash a cup.", important: false, done: false},
  {id: 164, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 165, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 166, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 167, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 168, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 169, label: "Pretend to be a rug.", important: false, done: false},
  {id: 170, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 171, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 172, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 173, label: "Wash a cup.", important: false, done: false},
  {id: 174, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 175, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 176, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 177, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 178, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 179, label: "Pretend to be a rug.", important: false, done: false},
  {id: 180, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 181, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 182, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 183, label: "Wash a cup.", important: false, done: false},
  {id: 184, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 185, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 186, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 187, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 188, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 189, label: "Pretend to be a rug.", important: false, done: false},
  {id: 190, label: "Clean a floor that's already clean to see if you can make it even more clean.", important: false, done: false},
  {id: 191, label: "Take everything in your cupboard and sort it by alphabetical order.", important: false, done: false},
  {id: 192, label: "Eat half a bag of plain rice cakes.", important: false, done: false},
  {id: 193, label: "Wash a cup.", important: false, done: false},
  {id: 194, label: "Stare at your wall. If there is anything on it, take it off, then keep staring.", important: false, done: false},
  {id: 195, label: "Go to Walgreens 3 hours before it opens.", important: false, done: false},
  {id: 196, label: "Keep checking your wallet to see if money ever magically appears.", important: false, done: false},
  {id: 197, label: "Do your taxes early so you'll have time to help other people with taxes later.", important: false, done: false},
  {id: 198, label: "Neatly fold all of your socks.", important: false, done: false},
  {id: 199, label: "Pretend to be a rug.", important: false, done: false},
]